spring.application.name=backend-api
server.port=8080


spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?user=postgres.jgntcrkhsodqvanqvycr&password=${SUPABASE_DB_PASSWORD}&prepareThreshold=0

# Note: Ensure you replace [YOUR-PASSWORD] in the string with your actual database password

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
# We use 'validate' because you already created the tables perfectly in Supabase.
# This prevents Spring from accidentally deleting or altering your schema.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true